### ISSUE TITLE
MIP render

### ISSUE THREAD

**Issue by haibinswe** [rordenlab/MRIcroGL#41]
It looks like that MIP rendering results in a 3D image, and the image can be rotated or flipped from any angle. So if the MIP rendering results a 3D image, can we save that 3D image into Nifti format image? If not, why the MIP rendering looks like a 3D image?

**Comment by neurolabusc** [comment]
The [Maximum Intensity Projection](https://en.wikipedia.org/wiki/Maximum_intensity_projection) takes a 3D image as input and generates a 2D image as output. It is like a 2D Xray that only detects the brightest object in the path of each ray. Since MIP renderings are 2D, it makes sense to save them as 2D images like PNG rather than 3D volumes like NIfTI. As the wikipedia page shows, you can make a movie of 2D MIP images to help the viewer appreciate depth.

**Comment by haibinswe** [comment]
So what we actually see from the MIP rendering in MRIcroGL is a 2D image or 2D projection,  Although  there is a 3D contour in the MIP rendering? And I want to know what happened when I rotated the MIP rendering images, maybe the image is 2D MIP image generated from the rotated 3D volume, or generated from the ray that parallel to our viewpoint?

**Comment by neurolabusc** [comment]
The Maximim intensity projection [MIP](https://pubs.rsna.org/doi/abs/10.1148/radiographics.17.2.9084083?journalCode=radiographics) is records the brightest value from the perspective of the camera, regardless of depth. The appearance depends on the brightness of the voxels and the position of the camera.
![mip](https://user-images.githubusercontent.com/8930807/168271587-776eb850-5fbc-4e66-b171-ad348523100e.jpeg)
