### ISSUE TITLE
Affine transform show in renderer?

### ISSUE THREAD

**Issue by shangjiaxuan** [rordenlab/MRIcroGL#50]
It seems affine transforms in NIfTI are not calculated into the MVP matrix in `glvolume2.pas`. How do I add that if needed for certain visualizations?

Consider this kind of layer to layer scan, with each layer's displacement not perpendicular to layer itself:
![Untitled Diagram drawio](https://user-images.githubusercontent.com/34389517/227497573-7668152a-cd94-4dba-8914-9cf026d14458.png)![Untitled Diagram1 drawio](https://user-images.githubusercontent.com/34389517/227499945-6c809e5f-4ccc-4932-b391-aeb3b7bd1835.png)

**Comment by shangjiaxuan** [comment]
This type of layered image info is expected in 3D backscatter imaging.

**Comment by neurolabusc** [comment]
MRIcroGL is able to use the S-Form and Q-Form to orient the closest orthogonal orientation and scale. However, it retains rectangular voxels. So with respect to the [affine](https://en.wikipedia.org/wiki/Affine_transformation) if handles the rotation, translation and scale but ignores the shear. 

You may want to look at [NiiVue](https://niivue.github.io/niivue/features/shear.html) or FSLeyes, both of which can show voxels in either image space or world space. You need to be aware that the [NIfTI](https://brainder.org/2012/09/23/the-nifti-file-format/) format has two spatial representations: the Q-Form (quaternion) stores 9 degrees of freedom (translation, rotation, scale each in 3 dimensions) while the S-Form (matrix) stores 12 DoF (adding shear). Therefore, to preserve shear you must properly define the S-Form of your NIfTI header.


Since most tools (including those built using the popular VTK library) assume that volumes do not have shear, another alternative is to resample your data into a large volume. If your source data is in DICOM format, dcm2niix can [do this for you](https://github.com/rordenlab/dcm2niix/issues/253). For sample DICOM and dcm2niix converted data, see [dcm_qa_ct](https://github.com/neurolabusc/dcm_qa_ct) where the DICOM images have gantry tilt, and dcm2nixi creates two volumes: one where the shear is reported in the S-Form, the other (`_tilt`) where the data is resampled.

**Comment by shangjiaxuan** [comment]
@neurolabusc Thanks for pointing out, it seems NiiVue is pretty fit for my use! My files are not from prebuilt commercial systems that comes with DICOM format, but instead we are developing new systems and thus chose Nifti as a simple format for storing scintilator or semiconductor detector event count. DICOM is simply an overkill for prototypes.
